spring.config.import=file:.env[.properties]
server.port=${DEV_PORT}

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.http.server.reactive=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG
logging.level.reactor.netty=DEBUG
logging.level.redisratelimiter=DEBUG
